module.exports = {
  TARGET_NUMBER: "6287731239611@c.us", 
  // RSS Feeds - pilih yang paling cepat update
  RSS_FEEDS: [
    {
      name: "CNBC Indonesia",
      url: "https://www.cnbcindonesia.com/news/rss",
    },
    {
      name: "Detik Finance",
      url: "https://rss.detik.com/index.php/detikfinance",
    },
    {
      name: "Bloomberg",
      url: "https://feeds.bloomberg.com/markets/news.rss",
    },
    {
      name: "Trump X",
      url: "https://rss.app/feeds/BWtF63VPo4skL4YB.xml",
    },
  ],

  // Interval dalam menit
  INTERVAL_MINUTES: 1,
  // Maksimal berita per feed
  MAX_NEWS_PER_FEED: 3,
  // Keywords untuk filter (kosongkan untuk semua berita)
  FILTER_KEYWORDS: [
    //     # MICIN COINS / NEW & RISKY PROJECTS
    "shitcoin",
    "altcoin",
    "airdrop",
    "pump",
    "dump",
    "rugpull",
    "honeypot",
    "memecoin",
    "presale",
    "pre-sale",
    "ido",
    "ico",
    "ieo",
    "new token",
    "crypto gem",
    "moonshot",
    "microcap",
    "low cap",
    "hidden gem",
    "gem alert",
    "new launch",
    "pinksale",
    "dxsale",
    "uniswap gem",
    "fair launch",
    "sniper bot",
    "bot trading",
    "launchpad",
    "token sale",
    "100x",
    "10x",
    "x100",

    //     # GENERAL CRYPTO & BLOCKCHAIN
    "bitcoin",
    "btc",
    "satoshi",
    "halving",
    "ethereum",
    "eth",
    "gas fee",
    "staking",
    "airdrops",
    "layer 1",
    "layer 2",
    "solana",
    "sol",
    "binance",
    "bnb",
    "arbitrum",
    "arb",
    "optimism",
    "op",
    "zksync",
    "zk rollup",
    "polygon",
    "matic",
    "blast",
    "base",
    "sepolia",
    "aptos",
    "sui",
    "near",
    "hedera",
    "cosmos",
    "atom",
    "avalanche",
    "avax",
    "phantom",
    "fantom",
    "tron",
    "trx",
    "ton",
    "toncoin",
    "blockchain",
    "defi",
    "nft",
    "dapp",
    "crypto",
    "tokenomics",
    "crypto project",

    //     # TECHNICAL ANALYSIS / TRADING TERMS
    "bullish",
    "bearish",
    "breakout",
    "resistance",
    "support",
    "trendline",
    "volume",
    "macd",
    "rsi",
    "liquidation",
    "funding rate",
    "open interest",
    "price action",
    "market structure",
    "fibonacci",
    "order block",
    "supply zone",
    "demand zone",
    "divergence",
    "long",
    "short",
    "futures",
    "leverage",
    "perpetual",
    "price pump",
    "chart pattern",
    "technical setup",

    //     # ECONOMIC / STOCKS / MACRO
    "dow jones",
    "nasdaq",
    "s&p",
    "sp500",
    "market crash",
    "correction",
    "recession",
    "inflation",
    "deflation",
    "stagflation",
    "gdp",
    "cpi",
    "ppi",
    "fomc",
    "interest rate",
    "rate hike",
    "rate cut",
    "suku bunga",
    "unemployment",
    "jobless claims",
    "job report",
    "treasury",
    "bond yield",
    "ipo",
    "dividend",
    "buyback",
    "stock split",
    "earning report",
    "quarterly earnings",

    //     # COMMODITIES / GOLD / OIL
    "gold",
    "silver",
    "oil",
    "crude",
    "brent",
    "commodity",
    "precious metals",
    "nickel",
    "palm oil",
    "wti",
    "copper",
    "natural gas",
    "uranium",
    "coal",
    "energy market",

    //     # CONFLICT / WAR / GEOPOLITICS
    "war",
    "conflict",
    "invasion",
    "military",
    "tensions",
    "missile",
    "drone strike",
    "nuclear",
    "bunker",
    "ukraine",
    "russia",
    "israel",
    "palestine",
    "gaza",
    "iran",
    "china",
    "taiwan",
    "north korea",
    "syria",
    "nato",
    "biden",
    "putin",
    "xi jinping",
    "sanctions",
    "airstrike",
    "border conflict",
    "proxy war",
    "geopolitical",
    "UN",
    "diplomatic",
    "diplomacy",

    //     # WHALE / ON-CHAIN SIGNALS
    "whale alert",
    "large transfer",
    "dormant wallet",
    "on-chain",
    "wallet moved",
    "exchange inflow",
    "exchange outflow",
    "binance transfer",
    "huge deposit",
    "massive withdrawal",
    "eth transfer",
    "btc transfer",
    "address activated",
    "whale",
    "shark",
    "wallet reactivation",

    //     # HYPE / VIRAL TRENDS
    "to the moon",
    "moon",
    "fomo",
    "hype",
    "trending coin",
    "viral token",
    "gm",
    "wen",
    "next 100x",
    "hot coin",
    "degen",
    "crypto twitter",
    "altseason",
    "season is coming",
    "bullrun",
    "going parabolic",
    "x100 gem",
    "diamond hands",
    "lambo",
    "green candle",
    "rekt",
    "influencer pump",

    //     # TECH / REGULATIONS / BIG NAMES
    "sec",
    "regulation",
    "crypto regulation",
    "etf",
    "bitcoin etf",
    "blackrock",
    "grayscale",
    "vaneck",
    "fidelity",
    "coinbase",
    "doj",
    "cex",
    "dex",
    "custody",
    "hot wallet",
    "cold wallet",
    "ledger",
    "metamask",
    "trezor",
    "compliance",
    "anti-money laundering",
    "kyc",
    "aml",
    "approval",

    //     # SCAM / EXPLOITS / SECURITY
    "scam",
    "hack",
    "phishing",
    "rug",
    "exploit",
    "bridge hack",
    "bridge exploit",
    "flash loan",
    "security breach",
    "wallet drained",
    "malicious contract",
    "exit scam",
    "vulnerability",
    "attack",
    "contract bug",
    "bridge vulnerability",
    "token exploit",
    "project hacked",
  ],
};
