const RSSParser = require('./rssParser');

class NewsFormatter {
  static formatNewsMessage(newsItems) {
    if (!newsItems || newsItems.length === 0) {
      return '📰 *Update Berita* 📰\n\n❌ Tidak ada berita baru yang sesuai filter.';
    }

    const header = `📰 *UPDATE BERITA TERKINI* 📰\n🕒 ${new Date().toLocaleString('id-ID')}\n\n`;
    
    const newsText = newsItems.map((item, index) => {
      return `${index + 1}. ${RSSParser.formatNewsItem(item, item.sourceName)}`;
    }).join('\n');

    const footer = `\n📊 Total: ${newsItems.length} berita\n⚡ Auto-generated by RSS Bot`;
    
    return header + newsText + footer;
  }

  static formatErrorMessage(error) {
    return `❌ *Error Update Berita* ❌\n\n🔧 ${error.message}\n⏰ ${new Date().toLocaleString('id-ID')}`;
  }
}

module.exports = NewsFormatter;
